# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'central.ui'
#
# Created: Mon Jan  4 23:49:19 2016
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(916, 523)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../pfc/qtmodel/PNG/8.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 80, 591, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(290, 10, 20, 71))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(10, 170, 591, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 100, 581, 71))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.fichero_edit = QtGui.QLineEdit(self.groupBox_2)
        self.fichero_edit.setGeometry(QtCore.QRect(10, 30, 481, 31))
        self.fichero_edit.setText(_fromUtf8(""))
        self.fichero_edit.setReadOnly(True)
        self.fichero_edit.setObjectName(_fromUtf8("fichero_edit"))
        self.elegir_boton = QtGui.QPushButton(self.groupBox_2)
        self.elegir_boton.setGeometry(QtCore.QRect(500, 30, 71, 31))
        self.elegir_boton.setObjectName(_fromUtf8("elegir_boton"))
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 10, 281, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.nombreconf_edit = QtGui.QLineEdit(self.groupBox_4)
        self.nombreconf_edit.setGeometry(QtCore.QRect(10, 30, 181, 31))
        self.nombreconf_edit.setInputMask(_fromUtf8(""))
        self.nombreconf_edit.setText(_fromUtf8(""))
        self.nombreconf_edit.setObjectName(_fromUtf8("nombreconf_edit"))
        self.guardar_boton = QtGui.QPushButton(self.groupBox_4)
        self.guardar_boton.setGeometry(QtCore.QRect(200, 30, 71, 31))
        self.guardar_boton.setObjectName(_fromUtf8("guardar_boton"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 410, 581, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.nombre_edit = QtGui.QLineEdit(self.groupBox)
        self.nombre_edit.setGeometry(QtCore.QRect(10, 30, 411, 31))
        self.nombre_edit.setObjectName(_fromUtf8("nombre_edit"))
        self.guardar_como_boton = QtGui.QPushButton(self.groupBox)
        self.guardar_como_boton.setGeometry(QtCore.QRect(430, 30, 141, 31))
        self.guardar_como_boton.setObjectName(_fromUtf8("guardar_como_boton"))
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(10, 390, 591, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(10, 260, 591, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.groupBox_9 = QtGui.QGroupBox(Form)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 190, 581, 71))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.n_spin_2 = QtGui.QSpinBox(self.groupBox_9)
        self.n_spin_2.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.n_spin_2.setPrefix(_fromUtf8(""))
        self.n_spin_2.setMinimum(1)
        self.n_spin_2.setMaximum(20)
        self.n_spin_2.setObjectName(_fromUtf8("n_spin_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_9)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 20, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.m_spin_2 = QtGui.QSpinBox(self.groupBox_9)
        self.m_spin_2.setGeometry(QtCore.QRect(100, 30, 61, 31))
        self.m_spin_2.setMinimum(1)
        self.m_spin_2.setMaximum(20)
        self.m_spin_2.setObjectName(_fromUtf8("m_spin_2"))
        self.dividir_boton = QtGui.QPushButton(self.groupBox_9)
        self.dividir_boton.setGeometry(QtCore.QRect(420, 30, 71, 31))
        self.dividir_boton.setObjectName(_fromUtf8("dividir_boton"))
        self.unir_boton = QtGui.QPushButton(self.groupBox_9)
        self.unir_boton.setGeometry(QtCore.QRect(500, 30, 71, 31))
        self.unir_boton.setObjectName(_fromUtf8("unir_boton"))
        self.label = QtGui.QLabel(self.groupBox_9)
        self.label.setGeometry(QtCore.QRect(210, 40, 81, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.sep_spin = QtGui.QSpinBox(self.groupBox_9)
        self.sep_spin.setGeometry(QtCore.QRect(290, 30, 81, 31))
        self.sep_spin.setMaximum(200)
        self.sep_spin.setObjectName(_fromUtf8("sep_spin"))
        self.groupBox_8 = QtGui.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(630, 100, 281, 381))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.preview_label = QtGui.QLabel(self.groupBox_8)
        self.preview_label.setGeometry(QtCore.QRect(10, 30, 261, 301))
        self.preview_label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.preview_label.setFrameShadow(QtGui.QFrame.Raised)
        self.preview_label.setText(_fromUtf8(""))
        self.preview_label.setScaledContents(True)
        self.preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_label.setObjectName(_fromUtf8("preview_label"))
        self.preview_slider = QtGui.QSlider(self.groupBox_8)
        self.preview_slider.setGeometry(QtCore.QRect(10, 350, 221, 20))
        self.preview_slider.setOrientation(QtCore.Qt.Horizontal)
        self.preview_slider.setObjectName(_fromUtf8("preview_slider"))
        self.borrar_boton = QtGui.QPushButton(self.groupBox_8)
        self.borrar_boton.setGeometry(QtCore.QRect(240, 340, 31, 31))
        self.borrar_boton.setObjectName(_fromUtf8("borrar_boton"))
        self.line_6 = QtGui.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(600, 10, 20, 471))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.deshacer_boton = QtGui.QPushButton(Form)
        self.deshacer_boton.setGeometry(QtCore.QRect(630, 20, 121, 51))
        self.deshacer_boton.setObjectName(_fromUtf8("deshacer_boton"))
        self.rehacer_boton = QtGui.QPushButton(Form)
        self.rehacer_boton.setGeometry(QtCore.QRect(780, 20, 121, 51))
        self.rehacer_boton.setObjectName(_fromUtf8("rehacer_boton"))
        self.line_7 = QtGui.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(620, 80, 291, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.groupBox_10 = QtGui.QGroupBox(Form)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 280, 371, 111))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.todas_radio = QtGui.QRadioButton(self.groupBox_10)
        self.todas_radio.setGeometry(QtCore.QRect(10, 20, 71, 26))
        self.todas_radio.setChecked(True)
        self.todas_radio.setObjectName(_fromUtf8("todas_radio"))
        self.previsualizada_radio = QtGui.QRadioButton(self.groupBox_10)
        self.previsualizada_radio.setGeometry(QtCore.QRect(10, 40, 121, 26))
        self.previsualizada_radio.setObjectName(_fromUtf8("previsualizada_radio"))
        self.quitar_boton = QtGui.QPushButton(self.groupBox_10)
        self.quitar_boton.setGeometry(QtCore.QRect(280, 10, 81, 61))
        self.quitar_boton.setFlat(False)
        self.quitar_boton.setObjectName(_fromUtf8("quitar_boton"))
        self.top_spin = QtGui.QSpinBox(self.groupBox_10)
        self.top_spin.setGeometry(QtCore.QRect(170, 10, 51, 21))
        self.top_spin.setMaximum(500)
        self.top_spin.setObjectName(_fromUtf8("top_spin"))
        self.left_spin = QtGui.QSpinBox(self.groupBox_10)
        self.left_spin.setGeometry(QtCore.QRect(140, 30, 51, 21))
        self.left_spin.setMaximum(500)
        self.left_spin.setObjectName(_fromUtf8("left_spin"))
        self.right_spin = QtGui.QSpinBox(self.groupBox_10)
        self.right_spin.setGeometry(QtCore.QRect(200, 30, 51, 21))
        self.right_spin.setMaximum(500)
        self.right_spin.setObjectName(_fromUtf8("right_spin"))
        self.bottom_spin = QtGui.QSpinBox(self.groupBox_10)
        self.bottom_spin.setGeometry(QtCore.QRect(170, 50, 51, 21))
        self.bottom_spin.setMaximum(500)
        self.bottom_spin.setObjectName(_fromUtf8("bottom_spin"))
        self.auto_boton = QtGui.QPushButton(self.groupBox_10)
        self.auto_boton.setGeometry(QtCore.QRect(230, 80, 81, 21))
        self.auto_boton.setObjectName(_fromUtf8("auto_boton"))
        self.label_3 = QtGui.QLabel(self.groupBox_10)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 121, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.umbral_spin = QtGui.QSpinBox(self.groupBox_10)
        self.umbral_spin.setGeometry(QtCore.QRect(160, 80, 59, 21))
        self.umbral_spin.setMinimum(1)
        self.umbral_spin.setMaximum(100)
        self.umbral_spin.setSingleStep(5)
        self.umbral_spin.setProperty("value", 20)
        self.umbral_spin.setObjectName(_fromUtf8("umbral_spin"))
        self.line_9 = QtGui.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(390, 280, 20, 111))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(420, 280, 181, 111))
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.border_spin = QtGui.QSpinBox(self.groupBox_5)
        self.border_spin.setGeometry(QtCore.QRect(10, 50, 71, 31))
        self.border_spin.setMinimum(1)
        self.border_spin.setMaximum(200)
        self.border_spin.setProperty("value", 30)
        self.border_spin.setObjectName(_fromUtf8("border_spin"))
        self.negro_boton = QtGui.QPushButton(self.groupBox_5)
        self.negro_boton.setGeometry(QtCore.QRect(100, 30, 71, 31))
        self.negro_boton.setObjectName(_fromUtf8("negro_boton"))
        self.blanco_boton = QtGui.QPushButton(self.groupBox_5)
        self.blanco_boton.setGeometry(QtCore.QRect(100, 70, 71, 31))
        self.blanco_boton.setObjectName(_fromUtf8("blanco_boton"))
        self.line_8 = QtGui.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(10, 480, 901, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.progress_bar = QtGui.QProgressBar(Form)
        self.progress_bar.setGeometry(QtCore.QRect(460, 500, 441, 16))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.msg_label = QtGui.QLabel(Form)
        self.msg_label.setGeometry(QtCore.QRect(60, 490, 391, 31))
        self.msg_label.setObjectName(_fromUtf8("msg_label"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 490, 41, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.logo_button = QtGui.QPushButton(Form)
        self.logo_button.setGeometry(QtCore.QRect(20, 10, 261, 71))
        self.logo_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo_button.setIcon(icon1)
        self.logo_button.setIconSize(QtCore.QSize(260, 200))
        self.logo_button.setDefault(False)
        self.logo_button.setFlat(True)
        self.logo_button.setObjectName(_fromUtf8("logo_button"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "PnPCards", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Ficheros de origen de las cartas", None, QtGui.QApplication.UnicodeUTF8))
        self.fichero_edit.setPlaceholderText(QtGui.QApplication.translate("Form", "Elige los ficheros de origen", None, QtGui.QApplication.UnicodeUTF8))
        self.elegir_boton.setText(QtGui.QApplication.translate("Form", "Elegir", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Guardar configuración", None, QtGui.QApplication.UnicodeUTF8))
        self.nombreconf_edit.setPlaceholderText(QtGui.QApplication.translate("Form", "Nombre de la configuracion", None, QtGui.QApplication.UnicodeUTF8))
        self.guardar_boton.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.nombre_edit.setPlaceholderText(QtGui.QApplication.translate("Form", "Nombre del juego", None, QtGui.QApplication.UnicodeUTF8))
        self.guardar_como_boton.setText(QtGui.QApplication.translate("Form", "Guardar como ...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Form", "Filas, columnas y separacion para dividir o unir las cartas", None, QtGui.QApplication.UnicodeUTF8))
        self.n_spin_2.setSuffix(QtGui.QApplication.translate("Form", " fil", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.m_spin_2.setSuffix(QtGui.QApplication.translate("Form", " col", None, QtGui.QApplication.UnicodeUTF8))
        self.dividir_boton.setText(QtGui.QApplication.translate("Form", "Dividir", None, QtGui.QApplication.UnicodeUTF8))
        self.unir_boton.setText(QtGui.QApplication.translate("Form", "Unir", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Separacion:", None, QtGui.QApplication.UnicodeUTF8))
        self.sep_spin.setSuffix(QtGui.QApplication.translate("Form", " px", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Form", "Previsualización", None, QtGui.QApplication.UnicodeUTF8))
        self.borrar_boton.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.deshacer_boton.setText(QtGui.QApplication.translate("Form", "Deshacer", None, QtGui.QApplication.UnicodeUTF8))
        self.rehacer_boton.setText(QtGui.QApplication.translate("Form", "Rehacer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Form", "Quitar margenes", None, QtGui.QApplication.UnicodeUTF8))
        self.todas_radio.setText(QtGui.QApplication.translate("Form", "Todas", None, QtGui.QApplication.UnicodeUTF8))
        self.previsualizada_radio.setText(QtGui.QApplication.translate("Form", "Previsualizada", None, QtGui.QApplication.UnicodeUTF8))
        self.quitar_boton.setText(QtGui.QApplication.translate("Form", "Quitar", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_boton.setText(QtGui.QApplication.translate("Form", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Umbral para auto:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Poner borde", None, QtGui.QApplication.UnicodeUTF8))
        self.border_spin.setSuffix(QtGui.QApplication.translate("Form", " px", None, QtGui.QApplication.UnicodeUTF8))
        self.negro_boton.setText(QtGui.QApplication.translate("Form", "Negro", None, QtGui.QApplication.UnicodeUTF8))
        self.blanco_boton.setText(QtGui.QApplication.translate("Form", "Blanco", None, QtGui.QApplication.UnicodeUTF8))
        self.msg_label.setText(QtGui.QApplication.translate("Form", "Mensaje en una botella", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Info:", None, QtGui.QApplication.UnicodeUTF8))

